{"uuid":"53df9b4c-9244-40a5-8d73-d8672901e69f","historyId":"f280feeefa4274a020ec62e0cb4f715a","fullName":"org.brit.tests.LoginTestPOSelenide.unsuccessLoginTest","labels":[{"name":"package","value":"org.brit.tests.LoginTestPOSelenide"},{"name":"testClass","value":"org.brit.tests.LoginTestPOSelenide"},{"name":"testMethod","value":"unsuccessLoginTest"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"SelemiumPractice15.03"},{"name":"subSuite","value":"org.brit.tests.LoginTestPOSelenide"},{"name":"host","value":"MacBook-Pro-Vladlen.local"},{"name":"thread","value":"97122@MacBook-Pro-Vladlen.local.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"unsuccessLoginTest","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"did not expect [Epic sadface: Username and password do not match any user in this service] but found [Epic sadface: Username and password do not match any user in this service]","trace":"java.lang.AssertionError: did not expect [Epic sadface: Username and password do not match any user in this service] but found [Epic sadface: Username and password do not match any user in this service]\n\tat org.testng.Assert.fail(Assert.java:110)\n\tat org.testng.Assert.failEquals(Assert.java:1581)\n\tat org.testng.Assert.assertNotEqualsImpl(Assert.java:156)\n\tat org.testng.Assert.assertNotEquals(Assert.java:2197)\n\tat org.testng.Assert.assertNotEquals(Assert.java:2219)\n\tat org.brit.tests.LoginTestPOSelenide.unsuccessLoginTest(LoginTestPOSelenide.java:42)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:829)\n\tat org.testng.TestRunner.run(TestRunner.java:602)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:437)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:330)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1176)\n\tat org.testng.TestNG.runSuites(TestNG.java:1099)\n\tat org.testng.TestNG.run(TestNG.java:1067)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1684344828812,"stop":1684344829315}